### PR TITLE
Add collapsibleTree

### PR DESCRIPTION
**Pull request by AdeelK93**

### CODE REVIEW

**Comment by AdeelK93** [comment]
The number of stars I have don't appear to be showing up correctly for collapsibleTree, or a couple other libraries like fluidSpline or slickR. Do you know why that might be? Thanks!

**Comment by hafen** [comment]
It takes about an hour for that to populate for newly added widgets (just added a few). If you don't see starts show up by tomorrow, please let me know.

**Comment by AdeelK93** [comment]
Ah gotcha, thanks!

**Comment by hafen** [comment]
btw do you have a twitter handle (for when I announce the widget?) If not that's okay.

**Comment by AdeelK93** [comment]
I don't really use my twitter, but I have one! https://twitter.com/AdeelKhan93

**Pull request merged**
