### PR TITLE
Added CanvasXpress Widget

### PR DESCRIPTION
**Pull request by neuhausi**

### CODE REVIEW

**Comment by neuhausi** [comment]
@hafen I just added a widget for canvasXpress. Please feedback and accept my request.
Regards,
Isaac

**Comment by MatthewRalston** [comment]
+1

**Comment by hafen** [comment]
Thanks for the nudge and sorry for the delay.  Looking at it right now.

**Comment by hafen** [comment]
Merged.  I changed the url to point to your github repo, as the jslib already links to canvasxpress.org.

**Comment by neuhausi** [comment]
Thank you

**Pull request merged**
