### PR TITLE
add calheatmapR

### PR DESCRIPTION
**Pull request by timelyportfolio**
add calheatmapR from @durtal.  Not sure what I need to do to plug in the gh meta script.

### CODE REVIEW

**Comment by hafen** [comment]
Thanks.  Can you add the thumbnail?

For the gh meta script, it does a git pull and will see the new yaml and will grab the stars for all repos in the yaml, so nothing to be done there.

**Comment by timelyportfolio** [comment]
@hafen, somehow I overwrote my changes, so I have redone.  hopefully, thumbnail and info in config.

**Comment by hafen** [comment]
Thanks!

**Comment by durtal** [comment]
Thanks both!! I just did a search on the gallery, and looks like @ramnathv developed a widget using calheatmap before me, without me realising, hope that's not a problem.

**Comment by hafen** [comment]
I think that's okay - this is part of the objective of this gallery, so I suppose it's serving it's purpose :).  If the interfaces and goals are similar, you might talk with @ramnathv about consolidating efforts.

**Comment by durtal** [comment]
I'm not sure if there is much more I can add, or that I have any goals, I initially wrote the package to explore how hard it was to create a widget, and thanks to @ramnathv and @timelyportfolio (+others) it was easier than I expected, and fun.  

I could perhaps adopt accepting a dataframe with dates and data, which is found in @ramnathv's package, while mine just accepts a named list.

Eventually, the more complex parts of the calheatmap library, the methods+events, could be added, allowing some functionality to scroll through the calendar via buttons, but these are beyond my (current) ability to recreate/port in R.  Perhaps one day.

Thanks for adding, and building a great site :+1:

**Pull request merged**
