### PR TITLE
googleway commit

### PR DESCRIPTION
**Pull request by ghost**
note: the `googleway` package is on CRAN, but the `google_map()` widget is not, so I have said `cran: false` in the .yaml file.

### CODE REVIEW

**Comment by hafen** [comment]
Cool package!  I think there is no problem using `cran: true` - `googleway` is an htmlwidget and is on CRAN, correct?

**Comment by SymbolixAU** [comment]
not quite - the `googleway` package on CRAN does not have the map widget in it. I started developing the widget after the release of the package, so the widget only exists on github.

**Comment by hafen** [comment]
I see.  It's up now - sorry for the delay.

**Comment by SymbolixAU** [comment]
I see the image is quite slow to render on the page - would you like a smaller one?
(or the same image, but resized)

**Comment by hafen** [comment]
Oh yeah I didn't notice but it is pretty big especially considering how many other images we are showing.  The space for each widget's image is 350x300.

**Pull request merged**
